// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"waffle"
)

var _ = waffle.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i64 get_client_id()")
  fmt.Fprintln(os.Stderr, "  void register_client_id(i32 block_id, i64 client_id)")
  fmt.Fprintln(os.Stderr, "  void async_get(sequence_id seq_id, string key)")
  fmt.Fprintln(os.Stderr, "  void async_put(sequence_id seq_id, string key, string value)")
  fmt.Fprintln(os.Stderr, "  void async_get_batch(sequence_id seq_id,  keys)")
  fmt.Fprintln(os.Stderr, "  void async_put_batch(sequence_id seq_id,  keys,  values)")
  fmt.Fprintln(os.Stderr, "  void init_db( keys,  values)")
  fmt.Fprintln(os.Stderr, "  void init_args(i64 B, i64 R, i64 F, i64 D, i64 C, i64 N)")
  fmt.Fprintln(os.Stderr, "  string get(string key)")
  fmt.Fprintln(os.Stderr, "  void put(string key, string value)")
  fmt.Fprintln(os.Stderr, "   get_batch( keys)")
  fmt.Fprintln(os.Stderr, "   mix_batch( keys,  values)")
  fmt.Fprintln(os.Stderr, "  void put_batch( keys,  values)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  var cfg *thrift.TConfiguration = nil
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransportConf(trans, cfg)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := waffle.NewWaffleThriftClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "get_client_id":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetClientID requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetClientID(context.Background()))
    fmt.Print("\n")
    break
  case "register_client_id":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RegisterClientID requires 2 args")
      flag.Usage()
    }
    tmp0, err63 := (strconv.Atoi(flag.Arg(1)))
    if err63 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    argvalue1, err64 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err64 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.RegisterClientID(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "async_get":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AsyncGet requires 2 args")
      flag.Usage()
    }
    arg65 := flag.Arg(1)
    mbTrans66 := thrift.NewTMemoryBufferLen(len(arg65))
    defer mbTrans66.Close()
    _, err67 := mbTrans66.WriteString(arg65)
    if err67 != nil {
      Usage()
      return
    }
    factory68 := thrift.NewTJSONProtocolFactory()
    jsProt69 := factory68.GetProtocol(mbTrans66)
    argvalue0 := waffle.NewSequenceID()
    err70 := argvalue0.Read(context.Background(), jsProt69)
    if err70 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.AsyncGet(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "async_put":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "AsyncPut requires 3 args")
      flag.Usage()
    }
    arg72 := flag.Arg(1)
    mbTrans73 := thrift.NewTMemoryBufferLen(len(arg72))
    defer mbTrans73.Close()
    _, err74 := mbTrans73.WriteString(arg72)
    if err74 != nil {
      Usage()
      return
    }
    factory75 := thrift.NewTJSONProtocolFactory()
    jsProt76 := factory75.GetProtocol(mbTrans73)
    argvalue0 := waffle.NewSequenceID()
    err77 := argvalue0.Read(context.Background(), jsProt76)
    if err77 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.AsyncPut(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "async_get_batch":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "AsyncGetBatch requires 2 args")
      flag.Usage()
    }
    arg80 := flag.Arg(1)
    mbTrans81 := thrift.NewTMemoryBufferLen(len(arg80))
    defer mbTrans81.Close()
    _, err82 := mbTrans81.WriteString(arg80)
    if err82 != nil {
      Usage()
      return
    }
    factory83 := thrift.NewTJSONProtocolFactory()
    jsProt84 := factory83.GetProtocol(mbTrans81)
    argvalue0 := waffle.NewSequenceID()
    err85 := argvalue0.Read(context.Background(), jsProt84)
    if err85 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg86 := flag.Arg(2)
    mbTrans87 := thrift.NewTMemoryBufferLen(len(arg86))
    defer mbTrans87.Close()
    _, err88 := mbTrans87.WriteString(arg86)
    if err88 != nil { 
      Usage()
      return
    }
    factory89 := thrift.NewTJSONProtocolFactory()
    jsProt90 := factory89.GetProtocol(mbTrans87)
    containerStruct1 := waffle.NewWaffleThriftAsyncGetBatchArgs()
    err91 := containerStruct1.ReadField2(context.Background(), jsProt90)
    if err91 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Keys
    value1 := argvalue1
    fmt.Print(client.AsyncGetBatch(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "async_put_batch":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "AsyncPutBatch requires 3 args")
      flag.Usage()
    }
    arg92 := flag.Arg(1)
    mbTrans93 := thrift.NewTMemoryBufferLen(len(arg92))
    defer mbTrans93.Close()
    _, err94 := mbTrans93.WriteString(arg92)
    if err94 != nil {
      Usage()
      return
    }
    factory95 := thrift.NewTJSONProtocolFactory()
    jsProt96 := factory95.GetProtocol(mbTrans93)
    argvalue0 := waffle.NewSequenceID()
    err97 := argvalue0.Read(context.Background(), jsProt96)
    if err97 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    arg98 := flag.Arg(2)
    mbTrans99 := thrift.NewTMemoryBufferLen(len(arg98))
    defer mbTrans99.Close()
    _, err100 := mbTrans99.WriteString(arg98)
    if err100 != nil { 
      Usage()
      return
    }
    factory101 := thrift.NewTJSONProtocolFactory()
    jsProt102 := factory101.GetProtocol(mbTrans99)
    containerStruct1 := waffle.NewWaffleThriftAsyncPutBatchArgs()
    err103 := containerStruct1.ReadField2(context.Background(), jsProt102)
    if err103 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Keys
    value1 := argvalue1
    arg104 := flag.Arg(3)
    mbTrans105 := thrift.NewTMemoryBufferLen(len(arg104))
    defer mbTrans105.Close()
    _, err106 := mbTrans105.WriteString(arg104)
    if err106 != nil { 
      Usage()
      return
    }
    factory107 := thrift.NewTJSONProtocolFactory()
    jsProt108 := factory107.GetProtocol(mbTrans105)
    containerStruct2 := waffle.NewWaffleThriftAsyncPutBatchArgs()
    err109 := containerStruct2.ReadField3(context.Background(), jsProt108)
    if err109 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.Values
    value2 := argvalue2
    fmt.Print(client.AsyncPutBatch(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "init_db":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "InitDb requires 2 args")
      flag.Usage()
    }
    arg110 := flag.Arg(1)
    mbTrans111 := thrift.NewTMemoryBufferLen(len(arg110))
    defer mbTrans111.Close()
    _, err112 := mbTrans111.WriteString(arg110)
    if err112 != nil { 
      Usage()
      return
    }
    factory113 := thrift.NewTJSONProtocolFactory()
    jsProt114 := factory113.GetProtocol(mbTrans111)
    containerStruct0 := waffle.NewWaffleThriftInitDbArgs()
    err115 := containerStruct0.ReadField1(context.Background(), jsProt114)
    if err115 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Keys
    value0 := argvalue0
    arg116 := flag.Arg(2)
    mbTrans117 := thrift.NewTMemoryBufferLen(len(arg116))
    defer mbTrans117.Close()
    _, err118 := mbTrans117.WriteString(arg116)
    if err118 != nil { 
      Usage()
      return
    }
    factory119 := thrift.NewTJSONProtocolFactory()
    jsProt120 := factory119.GetProtocol(mbTrans117)
    containerStruct1 := waffle.NewWaffleThriftInitDbArgs()
    err121 := containerStruct1.ReadField2(context.Background(), jsProt120)
    if err121 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Values
    value1 := argvalue1
    fmt.Print(client.InitDb(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "init_args":
    if flag.NArg() - 1 != 6 {
      fmt.Fprintln(os.Stderr, "InitArgs_ requires 6 args")
      flag.Usage()
    }
    argvalue0, err122 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err122 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err123 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err123 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2, err124 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err124 != nil {
      Usage()
      return
    }
    value2 := argvalue2
    argvalue3, err125 := (strconv.ParseInt(flag.Arg(4), 10, 64))
    if err125 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    argvalue4, err126 := (strconv.ParseInt(flag.Arg(5), 10, 64))
    if err126 != nil {
      Usage()
      return
    }
    value4 := argvalue4
    argvalue5, err127 := (strconv.ParseInt(flag.Arg(6), 10, 64))
    if err127 != nil {
      Usage()
      return
    }
    value5 := argvalue5
    fmt.Print(client.InitArgs_(context.Background(), value0, value1, value2, value3, value4, value5))
    fmt.Print("\n")
    break
  case "get":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Get requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Get(context.Background(), value0))
    fmt.Print("\n")
    break
  case "put":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Put requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Put(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "get_batch":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetBatch requires 1 args")
      flag.Usage()
    }
    arg131 := flag.Arg(1)
    mbTrans132 := thrift.NewTMemoryBufferLen(len(arg131))
    defer mbTrans132.Close()
    _, err133 := mbTrans132.WriteString(arg131)
    if err133 != nil { 
      Usage()
      return
    }
    factory134 := thrift.NewTJSONProtocolFactory()
    jsProt135 := factory134.GetProtocol(mbTrans132)
    containerStruct0 := waffle.NewWaffleThriftGetBatchArgs()
    err136 := containerStruct0.ReadField1(context.Background(), jsProt135)
    if err136 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Keys
    value0 := argvalue0
    fmt.Print(client.GetBatch(context.Background(), value0))
    fmt.Print("\n")
    break
  case "mix_batch":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "MixBatch requires 2 args")
      flag.Usage()
    }
    arg137 := flag.Arg(1)
    mbTrans138 := thrift.NewTMemoryBufferLen(len(arg137))
    defer mbTrans138.Close()
    _, err139 := mbTrans138.WriteString(arg137)
    if err139 != nil { 
      Usage()
      return
    }
    factory140 := thrift.NewTJSONProtocolFactory()
    jsProt141 := factory140.GetProtocol(mbTrans138)
    containerStruct0 := waffle.NewWaffleThriftMixBatchArgs()
    err142 := containerStruct0.ReadField1(context.Background(), jsProt141)
    if err142 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Keys
    value0 := argvalue0
    arg143 := flag.Arg(2)
    mbTrans144 := thrift.NewTMemoryBufferLen(len(arg143))
    defer mbTrans144.Close()
    _, err145 := mbTrans144.WriteString(arg143)
    if err145 != nil { 
      Usage()
      return
    }
    factory146 := thrift.NewTJSONProtocolFactory()
    jsProt147 := factory146.GetProtocol(mbTrans144)
    containerStruct1 := waffle.NewWaffleThriftMixBatchArgs()
    err148 := containerStruct1.ReadField2(context.Background(), jsProt147)
    if err148 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Values
    value1 := argvalue1
    fmt.Print(client.MixBatch(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "put_batch":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutBatch requires 2 args")
      flag.Usage()
    }
    arg149 := flag.Arg(1)
    mbTrans150 := thrift.NewTMemoryBufferLen(len(arg149))
    defer mbTrans150.Close()
    _, err151 := mbTrans150.WriteString(arg149)
    if err151 != nil { 
      Usage()
      return
    }
    factory152 := thrift.NewTJSONProtocolFactory()
    jsProt153 := factory152.GetProtocol(mbTrans150)
    containerStruct0 := waffle.NewWaffleThriftPutBatchArgs()
    err154 := containerStruct0.ReadField1(context.Background(), jsProt153)
    if err154 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Keys
    value0 := argvalue0
    arg155 := flag.Arg(2)
    mbTrans156 := thrift.NewTMemoryBufferLen(len(arg155))
    defer mbTrans156.Close()
    _, err157 := mbTrans156.WriteString(arg155)
    if err157 != nil { 
      Usage()
      return
    }
    factory158 := thrift.NewTJSONProtocolFactory()
    jsProt159 := factory158.GetProtocol(mbTrans156)
    containerStruct1 := waffle.NewWaffleThriftPutBatchArgs()
    err160 := containerStruct1.ReadField2(context.Background(), jsProt159)
    if err160 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Values
    value1 := argvalue1
    fmt.Print(client.PutBatch(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
