// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: oramExecutor.proto

package oramExecutor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestBatchORAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int64    `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Keys      []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values    []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *RequestBatchORAM) Reset() {
	*x = RequestBatchORAM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oramExecutor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchORAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchORAM) ProtoMessage() {}

func (x *RequestBatchORAM) ProtoReflect() protoreflect.Message {
	mi := &file_oramExecutor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchORAM.ProtoReflect.Descriptor instead.
func (*RequestBatchORAM) Descriptor() ([]byte, []int) {
	return file_oramExecutor_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBatchORAM) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RequestBatchORAM) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RequestBatchORAM) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RespondBatchORAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int64    `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Keys      []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values    []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *RespondBatchORAM) Reset() {
	*x = RespondBatchORAM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oramExecutor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondBatchORAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondBatchORAM) ProtoMessage() {}

func (x *RespondBatchORAM) ProtoReflect() protoreflect.Message {
	mi := &file_oramExecutor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondBatchORAM.ProtoReflect.Descriptor instead.
func (*RespondBatchORAM) Descriptor() ([]byte, []int) {
	return file_oramExecutor_proto_rawDescGZIP(), []int{1}
}

func (x *RespondBatchORAM) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RespondBatchORAM) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *RespondBatchORAM) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_oramExecutor_proto protoreflect.FileDescriptor

var file_oramExecutor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x72, 0x61, 0x6d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4f, 0x52, 0x41, 0x4d, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x5c, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x4f, 0x52, 0x41, 0x4d, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x32, 0x79, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x0c,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x52, 0x41, 0x4d, 0x1a,
	0x11, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x52,
	0x41, 0x4d, 0x12, 0x37, 0x0a, 0x06, 0x69, 0x6e, 0x69, 0x74, 0x44, 0x62, 0x12, 0x11, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x52, 0x41, 0x4d, 0x1a,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x6f,
	0x72, 0x61, 0x6d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x3b, 0x6f, 0x72, 0x61, 0x6d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oramExecutor_proto_rawDescOnce sync.Once
	file_oramExecutor_proto_rawDescData = file_oramExecutor_proto_rawDesc
)

func file_oramExecutor_proto_rawDescGZIP() []byte {
	file_oramExecutor_proto_rawDescOnce.Do(func() {
		file_oramExecutor_proto_rawDescData = protoimpl.X.CompressGZIP(file_oramExecutor_proto_rawDescData)
	})
	return file_oramExecutor_proto_rawDescData
}

var file_oramExecutor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oramExecutor_proto_goTypes = []any{
	(*RequestBatchORAM)(nil),     // 0: requestBatchORAM
	(*RespondBatchORAM)(nil),     // 1: respondBatchORAM
	(*wrapperspb.BoolValue)(nil), // 2: google.protobuf.BoolValue
}
var file_oramExecutor_proto_depIdxs = []int32{
	0, // 0: Executor.executeBatch:input_type -> requestBatchORAM
	0, // 1: Executor.initDb:input_type -> requestBatchORAM
	1, // 2: Executor.executeBatch:output_type -> respondBatchORAM
	2, // 3: Executor.initDb:output_type -> google.protobuf.BoolValue
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oramExecutor_proto_init() }
func file_oramExecutor_proto_init() {
	if File_oramExecutor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oramExecutor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestBatchORAM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oramExecutor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RespondBatchORAM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oramExecutor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oramExecutor_proto_goTypes,
		DependencyIndexes: file_oramExecutor_proto_depIdxs,
		MessageInfos:      file_oramExecutor_proto_msgTypes,
	}.Build()
	File_oramExecutor_proto = out.File
	file_oramExecutor_proto_rawDesc = nil
	file_oramExecutor_proto_goTypes = nil
	file_oramExecutor_proto_depIdxs = nil
}
